steps: 
- name: "gcr.io/cloud-builders/gcloud" 
args: 
[ 
"functions", 
"deploy", 
"kapiva-logger", 
"--region=asia-east1", 
"--runtime=python 3.7", 
"--trigger-http", 
"--entry-point=helloHttp", 
"--source=.", 
"--allow-unauthenticated", 
] 
timeout: "1200s" 
options: 
logging: CLOUD_LOGGING_ONLY

