steps:
  # Install dependencies
  - name: 'python:3.7'
    entrypoint: 'pip'
    args: ['install', '-r', 'requirements.txt']

  # Deploy to App Engine
  - name: 'gcr.io/cloud-builders/gcloud'
    args: ['app', 'deploy']
    timeout: '1600s'  # Increase timeout if necessary
